export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  thumbnailLink?: string;
  iconLink?: string;
  webViewLink?: string; // View in Drive
  webContentLink?: string; // Direct download
  size?: string;
  createdTime?: string;
  description?: string; // Standard Drive description
  aiSummary?: string; // Generated by Gemini
}

export interface AppConfig {
  driveApiKey: string;
  folderId: string;
  clientName: string;
}

export enum ViewMode {
  GRID = 'GRID',
  LIST = 'LIST',
}

export interface GeminiAnalysis {
  summary: string;
  tags: string[];
  professionalNote: string;
}